//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nconin_PropertyUATEntities : DbContext
    {
        public nconin_PropertyUATEntities()
            : base("name=nconin_PropertyUATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblcall> tblcalls { get; set; }
        public DbSet<tblcaller> tblcallers { get; set; }
        public DbSet<tblprakrutiproperty> tblprakrutiproperties { get; set; }
        public DbSet<tblstaff> tblstaffs { get; set; }
    }
}
