//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcall
    {
        public int idcall { get; set; }
        public Nullable<int> idcaller { get; set; }
        public Nullable<System.DateTime> dtinquirycall { get; set; }
        public Nullable<int> idstaff { get; set; }
        public string txtinquiryproject { get; set; }
        public string txtrequirementtype { get; set; }
        public Nullable<int> txtareareqmin { get; set; }
        public Nullable<int> txtareareqmax { get; set; }
        public string txtstatus { get; set; }
        public string txtbudgetmin { get; set; }
        public string txtbudgetmx { get; set; }
        public string txtpropertyoffered { get; set; }
        public string txtratequoted { get; set; }
        public string txttermasked { get; set; }
        public string txttermoffered { get; set; }
        public string txtinquirymedium { get; set; }
        public Nullable<System.DateTime> FollowUp_Date { get; set; }
        public string txtmeetingnotes { get; set; }
        public Nullable<System.DateTime> txtarrangedate { get; set; }
        public string txtpurpose { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyedDate { get; set; }
        public string ModifyedBy { get; set; }
    }
}
