//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string homephone { get; set; }
        public string pancard { get; set; }
        public string adharcard { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string password { get; set; }
        public sbyte status { get; set; }
        public string category { get; set; }
        public sbyte isActive { get; set; }
        public Nullable<System.DateTime> joining_date { get; set; }
    }
}
